name: golang_ci
on: [push]

jobs:
  build:
    name: all
    runs-on: ubuntu-latest
    steps:
      - name: set up
        uses: actions/setup-go@v1
        with:
          go-version: 1.15
        id: go
      - name: checkout
        uses: actions/checkout@v1
      # cache store
      - name: cache
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
        # golang-ci
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.29
      - name: test
        run: go test ./... -v
